### ISSUE TITLE
Fix the font?

### ISSUE THREAD

**Issue by DizzyDez** [DizzyDez/responsive-infographic#2]
I put in both links to the google font I wanted to use, and its working, in Chrome browser. Whenever I try it out in Firefox, the tabs for my masthead revert back to Times. I think the css I put in has cancelled out the svg code, because when it turn off one of the classes in the svg code (.st11), it seems to work. 

The Prevention at the bottom I have no idea how it is not working. I even double checked with the svg file to make sure presentation attribute were turned on. Should I go through the svg code to edit? 
@thomasjbradley

**Comment by thomasjbradley** [comment]
Yeah, I think you're right. The `.st11` and `.st14` classes have `font-family` on them. When I remove that the fonts seem to work much better.
