### ISSUE TITLE
I am trying something different, so I don't know if it's possible. 

### ISSUE THREAD

**Issue by DizzyDez** [DizzyDez/responsive-infographic#3]
I thought that the original image with the stripes in back would look good only in the larger screens, and I could take out the stripes for the mobile screen, so that the user can actually read what it says. Is this possible using the visisble property? or maybe the display: none? I have been trying to get this for a while and I haven't had any reaction in the browser whatsoever, so I might need some hints. 
@thomasjbradley

**Comment by thomasjbradley** [comment]
Hmmm... I’m actually not sure. There must be a way to hide it... I’ll have to look at it.
